name: Sync

on:
  push:
    branches:
      - main

jobs:
  json-server:
    name: json-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Sync files to all repositories
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.BOT_PAT }}
          PR_LABELS: false
          REVIEWERS: dalbitresb12
